# 衝突判定のブロックとの距離
distance: 0.1

# ジャンプ力の最小値
jumpMin: 0.5

# ジャンプ力の最大値
jumpMax: 2.0

# チャージによるジャンプ力上昇倍率
ratio: 0.2

# ジャンプ力 = ( ratio * チャージ時間(tick) + 1 ) * jumpPower

# ジャンプ倍率の対するピッチの変化量
pitchRatio: 2.0

# pitch = 1 / (ジャンプ倍率 * pitchRatio)

# 常時移動 (Block/Tick ?)
# 絶対軸
x: 0
z: 0

# 相対軸
forward: 0
right: 0

# 操作方法の表示時間 (tick)
tutorialTick: 0

# 更新頻度 (tick)
collisionTick: 1

# 参加時、リスポーン時の衝突判定無効時間 (tick)
noCollisionTick: 40

# 強制スペクテイターモード
forceSpectator: false

# 衝突時のキル
kill: false

# パーティクル
partilce: true

# ゲーム中のみジャンプを可能にするか
jumpGameOnly: false

# 衝突判定の無効化
training: false