# 衝突判定のブロックとの距離
distance: 0.1

# スタート時などの強制ジャンプ力
forceJump: 1.0

# ジャンプ力の最小値
jumpMin: 0.5

# ジャンプ力の最大値
jumpMax: 2.0

# チャージによるジャンプ力上昇倍率
ratio: 0.2

# ジャンプ力 = ( ratio * チャージ時間(tick) + 1 ) * jumpPower

# 効果音のピッチ 0.5 ~ 2.0

pitch: 0.5

# 常時移動 (Block/Tick ?)
# 絶対軸
x: 0
z: 0

# 相対軸
forward: 0
right: 0